version: '2'

services:
  lang-uk:
    build: .
    ports:
      - 5001:8080
    links:
    - ner-ms-uk
    - tokenize-ms
    - api_nlp_uk
  ner-ms-uk:
    image: chaliy/ner-ms:uk
    expose:
      - '8080'
  tokenize-ms:
    image: chaliy/tokenize-ms
    expose:
      - '8080'
  api_nlp_uk:
    image: chaliy/api_nlp_uk
    expose:
      - '8080'
